# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Admin do
  @moduledoc """
  API calls for all endpoints tagged `Admin`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  Revenue by month (admin)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%AdminRevenueGet200ResponseInner{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_revenue_get(Tesla.Env.client, keyword()) :: {:ok, [HookSniffAPI.Model.AdminRevenueGet200ResponseInner.t]} | {:error, Tesla.Env.t}
  def admin_revenue_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/revenue")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.AdminRevenueGet200ResponseInner}
    ])
  end

  @doc """
  Send SDK update notification to users

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (AdminSdkUpdatePostRequest): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_sdk_update_post(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def admin_sdk_update_post(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/admin/sdk-update")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  System-wide statistics (admin)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.SystemStats.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_stats_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.SystemStats.t} | {:error, Tesla.Env.t}
  def admin_stats_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/stats")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.SystemStats}
    ])
  end

  @doc """
  List all users (admin)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:per_page` (integer()): 

  ### Returns

  - `{:ok, HookSniffAPI.Model.PaginatedUsers.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_users_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.PaginatedUsers.t} | {:error, Tesla.Env.t}
  def admin_users_get(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :per_page => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/admin/users")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.PaginatedUsers}
    ])
  end

  @doc """
  Get user details (admin)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_users_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def admin_users_id_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/users/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Change user plan (admin)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `admin_users_id_plan_put_request` (AdminUsersIdPlanPutRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_users_id_plan_put(Tesla.Env.client, String.t, HookSniffAPI.Model.AdminUsersIdPlanPutRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def admin_users_id_plan_put(connection, id, admin_users_id_plan_put_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/admin/users/#{id}/plan")
      |> add_param(:body, :body, admin_users_id_plan_put_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Change user status (admin)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `admin_users_id_status_put_request` (AdminUsersIdStatusPutRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_users_id_status_put(Tesla.Env.client, String.t, HookSniffAPI.Model.AdminUsersIdStatusPutRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def admin_users_id_status_put(connection, id, admin_users_id_status_put_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/admin/users/#{id}/status")
      |> add_param(:body, :body, admin_users_id_status_put_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
