# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Alerts do
  @moduledoc """
  API calls for all endpoints tagged `Alerts`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List alert rules

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%AlertRule{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec alerts_get(Tesla.Env.client, keyword()) :: {:ok, [HookSniffAPI.Model.AlertRule.t]} | {:error, Tesla.Env.t}
  def alerts_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/alerts")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.AlertRule}
    ])
  end

  @doc """
  Delete alert rule

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec alerts_id_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def alerts_id_delete(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/alerts/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get alert rule

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.AlertRule.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec alerts_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, HookSniffAPI.Model.AlertRule.t} | {:error, Tesla.Env.t}
  def alerts_id_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/alerts/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.AlertRule}
    ])
  end

  @doc """
  Test an alert rule

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec alerts_id_test_post(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def alerts_id_test_post(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/alerts/#{id}/test")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Create alert rule

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `create_alert_request` (CreateAlertRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.AlertRule.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec alerts_post(Tesla.Env.client, HookSniffAPI.Model.CreateAlertRequest.t, keyword()) :: {:ok, HookSniffAPI.Model.AlertRule.t} | {:error, Tesla.Env.t}
  def alerts_post(connection, create_alert_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/alerts")
      |> add_param(:body, :body, create_alert_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, HookSniffAPI.Model.AlertRule}
    ])
  end
end
