# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Analytics do
  @moduledoc """
  API calls for all endpoints tagged `Analytics`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  Delivery trend over time

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:range` (String.t): 

  ### Returns

  - `{:ok, HookSniffAPI.Model.DeliveryTrendResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec analytics_deliveries_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.DeliveryTrendResponse.t} | {:error, Tesla.Env.t}
  def analytics_deliveries_get(connection, opts \\ []) do
    optional_params = %{
      :range => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/analytics/deliveries")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.DeliveryTrendResponse}
    ])
  end

  @doc """
  Latency trend over time

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:range` (String.t): 

  ### Returns

  - `{:ok, HookSniffAPI.Model.LatencyTrendResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec analytics_latency_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.LatencyTrendResponse.t} | {:error, Tesla.Env.t}
  def analytics_latency_get(connection, opts \\ []) do
    optional_params = %{
      :range => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/analytics/latency")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.LatencyTrendResponse}
    ])
  end

  @doc """
  Success rate metrics

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:range` (String.t): 

  ### Returns

  - `{:ok, HookSniffAPI.Model.SuccessRateResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec analytics_success_rate_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.SuccessRateResponse.t} | {:error, Tesla.Env.t}
  def analytics_success_rate_get(connection, opts \\ []) do
    optional_params = %{
      :range => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/analytics/success-rate")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.SuccessRateResponse}
    ])
  end
end
