# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Applications do
  @moduledoc """
  API calls for all endpoints tagged `Applications`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List applications
  Returns all applications for the authenticated user

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%Application{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec applications_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, [HookSniffAPI.Model.Application.t]} | {:error, Tesla.Env.t}
  def applications_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/applications")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.Application},
      {401, false}
    ])
  end

  @doc """
  Delete application

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec applications_id_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def applications_id_delete(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/applications/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, false}
    ])
  end

  @doc """
  Get application

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.Application.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec applications_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, HookSniffAPI.Model.Application.t} | {:error, Tesla.Env.t}
  def applications_id_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/applications/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.Application},
      {404, false}
    ])
  end

  @doc """
  Update application

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:body` (ApplicationsIdPutRequest): 

  ### Returns

  - `{:ok, HookSniffAPI.Model.Application.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec applications_id_put(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, HookSniffAPI.Model.Application.t} | {:error, Tesla.Env.t}
  def applications_id_put(connection, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/applications/#{id}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.Application},
      {404, false}
    ])
  end

  @doc """
  Create application

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `applications_post_request` (ApplicationsPostRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.Application.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec applications_post(Tesla.Env.client, HookSniffAPI.Model.ApplicationsPostRequest.t, keyword()) :: {:ok, nil} | {:ok, HookSniffAPI.Model.Application.t} | {:error, Tesla.Env.t}
  def applications_post(connection, applications_post_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/applications")
      |> add_param(:body, :body, applications_post_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, HookSniffAPI.Model.Application},
      {400, false},
      {401, false}
    ])
  end
end
