# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Contact do
  @moduledoc """
  API calls for all endpoints tagged `Contact`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  Send contact form message

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `contact_request` (ContactRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.ContactResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec contact_post(Tesla.Env.client, HookSniffAPI.Model.ContactRequest.t, keyword()) :: {:ok, nil} | {:ok, HookSniffAPI.Model.ContactResponse.t} | {:error, Tesla.Env.t}
  def contact_post(connection, contact_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/contact")
      |> add_param(:body, :body, contact_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.ContactResponse},
      {400, false}
    ])
  end
end
