# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.CustomerPortal do
  @moduledoc """
  API calls for all endpoints tagged `CustomerPortal`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List API keys (portal)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%ApiKeyInfo{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_api_keys_get(Tesla.Env.client, keyword()) :: {:ok, [HookSniffAPI.Model.ApiKeyInfo.t]} | {:error, Tesla.Env.t}
  def portal_api_keys_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/portal/api-keys")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.ApiKeyInfo}
    ])
  end

  @doc """
  Revoke API key (portal)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `key_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_api_keys_key_id_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def portal_api_keys_key_id_delete(connection, key_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/portal/api-keys/#{key_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Create API key (portal)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.CreateApiKeyResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_api_keys_post(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.CreateApiKeyResponse.t} | {:error, Tesla.Env.t}
  def portal_api_keys_post(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/portal/api-keys")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, HookSniffAPI.Model.CreateApiKeyResponse}
    ])
  end

  @doc """
  Get portal configuration

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_config_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def portal_config_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/portal/config")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Update portal configuration

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_config_post(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def portal_config_post(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/portal/config")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get portal embed code

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_embed_code_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def portal_embed_code_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/portal/embed-code")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get portal profile

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.PortalProfile.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_me_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.PortalProfile.t} | {:error, Tesla.Env.t}
  def portal_me_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/portal/me")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.PortalProfile}
    ])
  end

  @doc """
  Update portal profile

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `update_profile_request` (UpdateProfileRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_me_put(Tesla.Env.client, HookSniffAPI.Model.UpdateProfileRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def portal_me_put(connection, update_profile_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/portal/me")
      |> add_param(:body, :body, update_profile_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get notification preferences (portal)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.NotificationPreferences.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_notifications_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.NotificationPreferences.t} | {:error, Tesla.Env.t}
  def portal_notifications_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/portal/notifications")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.NotificationPreferences}
    ])
  end

  @doc """
  Update notification preferences (portal)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `update_notification_preferences` (UpdateNotificationPreferences): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.PortalNotificationsPut200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_notifications_put(Tesla.Env.client, HookSniffAPI.Model.UpdateNotificationPreferences.t, keyword()) :: {:ok, HookSniffAPI.Model.PortalNotificationsPut200Response.t} | {:error, Tesla.Env.t}
  def portal_notifications_put(connection, update_notification_preferences, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/portal/notifications")
      |> add_param(:body, :body, update_notification_preferences)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.PortalNotificationsPut200Response}
    ])
  end

  @doc """
  Get plan info (portal)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.SubscriptionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_plan_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.SubscriptionResponse.t} | {:error, Tesla.Env.t}
  def portal_plan_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/portal/plan")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.SubscriptionResponse}
    ])
  end

  @doc """
  Get usage (portal)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.UsageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec portal_usage_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.UsageResponse.t} | {:error, Tesla.Env.t}
  def portal_usage_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/portal/usage")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.UsageResponse}
    ])
  end
end
