# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Devices do
  @moduledoc """
  API calls for all endpoints tagged `Devices`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List registered devices

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%DeviceTokenResponse{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec devices_get(Tesla.Env.client, keyword()) :: {:ok, [HookSniffAPI.Model.DeviceTokenResponse.t]} | {:error, Tesla.Env.t}
  def devices_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/devices")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.DeviceTokenResponse}
    ])
  end

  @doc """
  Register device for push notifications

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `register_device_request` (RegisterDeviceRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.DeviceTokenResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec devices_post(Tesla.Env.client, HookSniffAPI.Model.RegisterDeviceRequest.t, keyword()) :: {:ok, HookSniffAPI.Model.DeviceTokenResponse.t} | {:error, Tesla.Env.t}
  def devices_post(connection, register_device_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/devices")
      |> add_param(:body, :body, register_device_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, HookSniffAPI.Model.DeviceTokenResponse}
    ])
  end

  @doc """
  Remove device token

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `token` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec devices_token_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def devices_token_delete(connection, token, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/devices/#{token}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
