# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Endpoints do
  @moduledoc """
  API calls for all endpoints tagged `Endpoints`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List all endpoints

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%Endpoint{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_get(Tesla.Env.client, keyword()) :: {:ok, [HookSniffAPI.Model.Endpoint.t]} | {:error, Tesla.Env.t}
  def endpoints_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/endpoints")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.Endpoint}
    ])
  end

  @doc """
  Delete endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_id_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def endpoints_id_delete(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/endpoints/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get endpoint by ID

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.Endpoint.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, HookSniffAPI.Model.Endpoint.t} | {:error, Tesla.Env.t}
  def endpoints_id_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/endpoints/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.Endpoint},
      {404, false}
    ])
  end

  @doc """
  Update endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `update_endpoint_request` (UpdateEndpointRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.Endpoint.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_id_put(Tesla.Env.client, String.t, HookSniffAPI.Model.UpdateEndpointRequest.t, keyword()) :: {:ok, HookSniffAPI.Model.Endpoint.t} | {:error, Tesla.Env.t}
  def endpoints_id_put(connection, id, update_endpoint_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/endpoints/#{id}")
      |> add_param(:body, :body, update_endpoint_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.Endpoint}
    ])
  end

  @doc """
  Update retry policy for an endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `retry_policy` (RetryPolicy): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.Endpoint.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_id_retry_policy_put(Tesla.Env.client, String.t, HookSniffAPI.Model.RetryPolicy.t, keyword()) :: {:ok, HookSniffAPI.Model.Endpoint.t} | {:error, Tesla.Env.t}
  def endpoints_id_retry_policy_put(connection, id, retry_policy, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/endpoints/#{id}/retry-policy")
      |> add_param(:body, :body, retry_policy)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.Endpoint}
    ])
  end

  @doc """
  Rotate endpoint signing secret

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.EndpointsIdRotateSecretPost200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_id_rotate_secret_post(Tesla.Env.client, String.t, keyword()) :: {:ok, HookSniffAPI.Model.EndpointsIdRotateSecretPost200Response.t} | {:error, Tesla.Env.t}
  def endpoints_id_rotate_secret_post(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/endpoints/#{id}/rotate-secret")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.EndpointsIdRotateSecretPost200Response}
    ])
  end

  @doc """
  Create a new endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `create_endpoint_request` (CreateEndpointRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.Endpoint.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_post(Tesla.Env.client, HookSniffAPI.Model.CreateEndpointRequest.t, keyword()) :: {:ok, HookSniffAPI.Model.Endpoint.t} | {:error, Tesla.Env.t}
  def endpoints_post(connection, create_endpoint_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/endpoints")
      |> add_param(:body, :body, create_endpoint_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, HookSniffAPI.Model.Endpoint}
    ])
  end
end
