# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Health do
  @moduledoc """
  API calls for all endpoints tagged `Health`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List endpoint health statuses

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%EndpointHealth{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoint_health_get(Tesla.Env.client, keyword()) :: {:ok, [HookSniffAPI.Model.EndpointHealth.t]} | {:error, Tesla.Env.t}
  def endpoint_health_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/endpoint-health")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.EndpointHealth}
    ])
  end

  @doc """
  Get specific endpoint health

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.EndpointHealth.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoint_health_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, HookSniffAPI.Model.EndpointHealth.t} | {:error, Tesla.Env.t}
  def endpoint_health_id_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/endpoint-health/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.EndpointHealth}
    ])
  end

  @doc """
  System status (public)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.SystemStatus.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec status_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.SystemStatus.t} | {:error, Tesla.Env.t}
  def status_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/status")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.SystemStatus},
      {503, HookSniffAPI.Model.SystemStatus}
    ])
  end
end
