# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.OutboundIPs do
  @moduledoc """
  API calls for all endpoints tagged `OutboundIPs`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  Get outbound IP addresses for firewall whitelisting

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.OutboundIpsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec outbound_ips_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.OutboundIpsResponse.t} | {:error, Tesla.Env.t}
  def outbound_ips_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/outbound-ips")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.OutboundIpsResponse}
    ])
  end
end
