# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.RateLimits do
  @moduledoc """
  API calls for all endpoints tagged `RateLimits`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  Delete rate limit for endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `endpoint_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec rate_limits_endpoint_id_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def rate_limits_endpoint_id_delete(connection, endpoint_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/rate-limits/#{endpoint_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get rate limit for endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `endpoint_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec rate_limits_endpoint_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def rate_limits_endpoint_id_get(connection, endpoint_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/rate-limits/#{endpoint_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Set rate limit for endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `endpoint_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec rate_limits_endpoint_id_post(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def rate_limits_endpoint_id_post(connection, endpoint_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/rate-limits/#{endpoint_id}")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  List rate limits

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec rate_limits_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def rate_limits_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/rate-limits")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
