# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Routing do
  @moduledoc """
  API calls for all endpoints tagged `Routing`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  Get endpoint health status

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.EndpointHealth.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_id_health_get(Tesla.Env.client, String.t, keyword()) :: {:ok, HookSniffAPI.Model.EndpointHealth.t} | {:error, Tesla.Env.t}
  def endpoints_id_health_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/endpoints/#{id}/health")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.EndpointHealth}
    ])
  end

  @doc """
  Get routing config for endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.RoutingInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_id_routing_get(Tesla.Env.client, String.t, keyword()) :: {:ok, HookSniffAPI.Model.RoutingInfo.t} | {:error, Tesla.Env.t}
  def endpoints_id_routing_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/endpoints/#{id}/routing")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.RoutingInfo}
    ])
  end

  @doc """
  Update routing config

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `update_routing_request` (UpdateRoutingRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.RoutingInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_id_routing_put(Tesla.Env.client, String.t, HookSniffAPI.Model.UpdateRoutingRequest.t, keyword()) :: {:ok, HookSniffAPI.Model.RoutingInfo.t} | {:error, Tesla.Env.t}
  def endpoints_id_routing_put(connection, id, update_routing_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/endpoints/#{id}/routing")
      |> add_param(:body, :body, update_routing_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.RoutingInfo}
    ])
  end
end
