# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Schemas do
  @moduledoc """
  API calls for all endpoints tagged `Schemas`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List registered schemas

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec schemas_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def schemas_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/schemas")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get schema by ID

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec schemas_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def schemas_id_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/schemas/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Validate an event against a schema

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `validate_event_request` (ValidateEventRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec schemas_id_validate_post(Tesla.Env.client, String.t, HookSniffAPI.Model.ValidateEventRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def schemas_id_validate_post(connection, id, validate_event_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/schemas/#{id}/validate")
      |> add_param(:body, :body, validate_event_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {422, false}
    ])
  end

  @doc """
  Register a new JSON Schema

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `register_schema_request` (RegisterSchemaRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec schemas_post(Tesla.Env.client, HookSniffAPI.Model.RegisterSchemaRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def schemas_post(connection, register_schema_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/schemas")
      |> add_param(:body, :body, register_schema_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end
end
