# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Search do
  @moduledoc """
  API calls for all endpoints tagged `Search`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  Search deliveries

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `q` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:status` (String.t): 
    - `:endpoint_id` (String.t): 
    - `:page` (integer()): 
    - `:per_page` (integer()): 

  ### Returns

  - `{:ok, HookSniffAPI.Model.SearchResult.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec search_get(Tesla.Env.client, String.t, keyword()) :: {:ok, HookSniffAPI.Model.SearchResult.t} | {:error, Tesla.Env.t}
  def search_get(connection, q, opts \\ []) do
    optional_params = %{
      :status => :query,
      :endpoint_id => :query,
      :page => :query,
      :per_page => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/search")
      |> add_param(:query, :q, q)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.SearchResult}
    ])
  end
end
