# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.ServiceTokens do
  @moduledoc """
  API calls for all endpoints tagged `ServiceTokens`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List service tokens
  Returns all service tokens for the authenticated user

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%ServiceToken{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec service_tokens_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, [HookSniffAPI.Model.ServiceToken.t]} | {:error, Tesla.Env.t}
  def service_tokens_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/service-tokens")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.ServiceToken},
      {401, false}
    ])
  end

  @doc """
  Delete service token

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec service_tokens_id_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def service_tokens_id_delete(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/service-tokens/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, false}
    ])
  end

  @doc """
  Update service token

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:body` (ServiceTokensIdPutRequest): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec service_tokens_id_put(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def service_tokens_id_put(connection, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/service-tokens/#{id}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, false}
    ])
  end

  @doc """
  Reveal service token
  Returns the full token value (only available once after creation, or via this endpoint)

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.ServiceTokensIdRevealPost200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec service_tokens_id_reveal_post(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, HookSniffAPI.Model.ServiceTokensIdRevealPost200Response.t} | {:error, Tesla.Env.t}
  def service_tokens_id_reveal_post(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/service-tokens/#{id}/reveal")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.ServiceTokensIdRevealPost200Response},
      {404, false}
    ])
  end

  @doc """
  Create a service token

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `service_tokens_post_request` (ServiceTokensPostRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.ServiceTokenCreateResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec service_tokens_post(Tesla.Env.client, HookSniffAPI.Model.ServiceTokensPostRequest.t, keyword()) :: {:ok, nil} | {:ok, HookSniffAPI.Model.ServiceTokenCreateResponse.t} | {:error, Tesla.Env.t}
  def service_tokens_post(connection, service_tokens_post_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/service-tokens")
      |> add_param(:body, :body, service_tokens_post_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, HookSniffAPI.Model.ServiceTokenCreateResponse},
      {401, false}
    ])
  end
end
