# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Stats do
  @moduledoc """
  API calls for all endpoints tagged `Stats`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  Get account statistics

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.StatsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec stats_get(Tesla.Env.client, keyword()) :: {:ok, HookSniffAPI.Model.StatsResponse.t} | {:error, Tesla.Env.t}
  def stats_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/stats")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.StatsResponse}
    ])
  end
end
