# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Teams do
  @moduledoc """
  API calls for all endpoints tagged `Teams`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List teams

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%Team{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec teams_get(Tesla.Env.client, keyword()) :: {:ok, [HookSniffAPI.Model.Team.t]} | {:error, Tesla.Env.t}
  def teams_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/teams")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.Team}
    ])
  end

  @doc """
  Get team details

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.TeamDetailResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec teams_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, HookSniffAPI.Model.TeamDetailResponse.t} | {:error, Tesla.Env.t}
  def teams_id_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/teams/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.TeamDetailResponse}
    ])
  end

  @doc """
  Invite a member to the team

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `invite_request` (InviteRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec teams_id_invite_post(Tesla.Env.client, String.t, HookSniffAPI.Model.InviteRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def teams_id_invite_post(connection, id, invite_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/teams/#{id}/invite")
      |> add_param(:body, :body, invite_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  List team members

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%TeamMember{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec teams_id_members_get(Tesla.Env.client, String.t, keyword()) :: {:ok, [HookSniffAPI.Model.TeamMember.t]} | {:error, Tesla.Env.t}
  def teams_id_members_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/teams/#{id}/members")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.TeamMember}
    ])
  end

  @doc """
  Remove member from team

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `uid` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec teams_id_members_uid_delete(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def teams_id_members_uid_delete(connection, id, uid, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/teams/#{id}/members/#{uid}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Change member role

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `uid` (String.t): 
  - `change_role_request` (ChangeRoleRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec teams_id_members_uid_role_put(Tesla.Env.client, String.t, String.t, HookSniffAPI.Model.ChangeRoleRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def teams_id_members_uid_role_put(connection, id, uid, change_role_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/teams/#{id}/members/#{uid}/role")
      |> add_param(:body, :body, change_role_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Create a team

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `create_team_request` (CreateTeamRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.Team.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec teams_post(Tesla.Env.client, HookSniffAPI.Model.CreateTeamRequest.t, keyword()) :: {:ok, HookSniffAPI.Model.Team.t} | {:error, Tesla.Env.t}
  def teams_post(connection, create_team_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/teams")
      |> add_param(:body, :body, create_team_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, HookSniffAPI.Model.Team}
    ])
  end
end
