# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Templates do
  @moduledoc """
  API calls for all endpoints tagged `Templates`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List available templates

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:category` (String.t): 

  ### Returns

  - `{:ok, [%WebhookTemplate{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec templates_get(Tesla.Env.client, keyword()) :: {:ok, [HookSniffAPI.Model.WebhookTemplate.t]} | {:error, Tesla.Env.t}
  def templates_get(connection, opts \\ []) do
    optional_params = %{
      :category => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/templates")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.WebhookTemplate}
    ])
  end

  @doc """
  Apply template to an endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `apply_template_request` (ApplyTemplateRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.ApplyTemplateResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec templates_id_apply_post(Tesla.Env.client, String.t, HookSniffAPI.Model.ApplyTemplateRequest.t, keyword()) :: {:ok, HookSniffAPI.Model.ApplyTemplateResponse.t} | {:error, Tesla.Env.t}
  def templates_id_apply_post(connection, id, apply_template_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/templates/#{id}/apply")
      |> add_param(:body, :body, apply_template_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.ApplyTemplateResponse}
    ])
  end

  @doc """
  Get template by ID

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.WebhookTemplate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec templates_id_get(Tesla.Env.client, String.t, keyword()) :: {:ok, HookSniffAPI.Model.WebhookTemplate.t} | {:error, Tesla.Env.t}
  def templates_id_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/templates/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.WebhookTemplate}
    ])
  end
end
