# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Api.Transforms do
  @moduledoc """
  API calls for all endpoints tagged `Transforms`.
  """

  alias HookSniffAPI.Connection
  import HookSniffAPI.RequestBuilder

  @doc """
  List transform rules for endpoint

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `endpoint_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%TransformRule{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_endpoint_id_transforms_get(Tesla.Env.client, String.t, keyword()) :: {:ok, [HookSniffAPI.Model.TransformRule.t]} | {:error, Tesla.Env.t}
  def endpoints_endpoint_id_transforms_get(connection, endpoint_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/endpoints/#{endpoint_id}/transforms")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.TransformRule}
    ])
  end

  @doc """
  Delete transform rule

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `endpoint_id` (String.t): 
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_endpoint_id_transforms_id_delete(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def endpoints_endpoint_id_transforms_id_delete(connection, endpoint_id, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/endpoints/#{endpoint_id}/transforms/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Update transform rule

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `endpoint_id` (String.t): 
  - `id` (String.t): 
  - `body` (map()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.TransformRule.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_endpoint_id_transforms_id_put(Tesla.Env.client, String.t, String.t, %{optional(String.t) => any()}, keyword()) :: {:ok, HookSniffAPI.Model.TransformRule.t} | {:error, Tesla.Env.t}
  def endpoints_endpoint_id_transforms_id_put(connection, endpoint_id, id, body, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/endpoints/#{endpoint_id}/transforms/#{id}")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, HookSniffAPI.Model.TransformRule}
    ])
  end

  @doc """
  Create transform rule

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `endpoint_id` (String.t): 
  - `create_transform_rule_request` (CreateTransformRuleRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, HookSniffAPI.Model.TransformRule.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_endpoint_id_transforms_post(Tesla.Env.client, String.t, HookSniffAPI.Model.CreateTransformRuleRequest.t, keyword()) :: {:ok, HookSniffAPI.Model.TransformRule.t} | {:error, Tesla.Env.t}
  def endpoints_endpoint_id_transforms_post(connection, endpoint_id, create_transform_rule_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/endpoints/#{endpoint_id}/transforms")
      |> add_param(:body, :body, create_transform_rule_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, HookSniffAPI.Model.TransformRule}
    ])
  end

  @doc """
  Test a transform rule

  ### Parameters

  - `connection` (HookSniffAPI.Connection): Connection to server
  - `endpoint_id` (String.t): 
  - `endpoints_endpoint_id_transforms_test_post_request` (EndpointsEndpointIdTransformsTestPostRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec endpoints_endpoint_id_transforms_test_post(Tesla.Env.client, String.t, HookSniffAPI.Model.EndpointsEndpointIdTransformsTestPostRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def endpoints_endpoint_id_transforms_test_post(connection, endpoint_id, endpoints_endpoint_id_transforms_test_post_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/endpoints/#{endpoint_id}/transforms/test")
      |> add_param(:body, :body, endpoints_endpoint_id_transforms_test_post_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
