# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminUsersIdStatusPutRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :is_active
  ]

  @type t :: %__MODULE__{
    :is_active => boolean() | nil
  }

  def decode(value) do
    value
  end
end

