# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminUsersIdGet200ResponseRecentDeliveriesInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :endpoint_id,
    :status,
    :event_type,
    :created_at,
    :attempt_count
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :endpoint_id => String.t | nil,
    :status => String.t | nil,
    :event_type => String.t | nil,
    :created_at => DateTime.t | nil,
    :attempt_count => integer() | nil
  }

  def decode(value) do
    value
  end
end

