# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminUsersIdGet200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :user,
    :endpoints,
    :recent_deliveries,
    :usage_stats
  ]

  @type t :: %__MODULE__{
    :user => HookSniffAPI.Model.UserSummary.t | nil,
    :endpoints => [HookSniffAPI.Model.AdminUsersIdGet200ResponseEndpointsInner.t] | nil,
    :recent_deliveries => [HookSniffAPI.Model.AdminUsersIdGet200ResponseRecentDeliveriesInner.t] | nil,
    :usage_stats => HookSniffAPI.Model.AdminUsersIdGet200ResponseUsageStats.t | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:user, :struct, HookSniffAPI.Model.UserSummary)
     |> Deserializer.deserialize(:endpoints, :list, HookSniffAPI.Model.AdminUsersIdGet200ResponseEndpointsInner)
     |> Deserializer.deserialize(:recent_deliveries, :list, HookSniffAPI.Model.AdminUsersIdGet200ResponseRecentDeliveriesInner)
     |> Deserializer.deserialize(:usage_stats, :struct, HookSniffAPI.Model.AdminUsersIdGet200ResponseUsageStats)
  end
end

