# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminUsersIdGet200ResponseEndpointsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :url,
    :description,
    :is_active,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :url => String.t | nil,
    :description => String.t | nil,
    :is_active => boolean() | nil,
    :created_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

