# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminFeatureFlagsIdPutRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description,
    :is_enabled,
    :rollout_percentage,
    :enabled_for_plans
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :description => String.t | nil,
    :is_enabled => boolean() | nil,
    :rollout_percentage => integer() | nil,
    :enabled_for_plans => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

