# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminUsersIdPlanPutRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :plan
  ]

  @type t :: %__MODULE__{
    :plan => String.t | nil
  }

  def decode(value) do
    value
  end
end

