# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminUsersIdGet200ResponseUsageStats do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :total_deliveries,
    :success_rate,
    :endpoints_count
  ]

  @type t :: %__MODULE__{
    :total_deliveries => integer() | nil,
    :success_rate => float() | nil,
    :endpoints_count => integer() | nil
  }

  def decode(value) do
    value
  end
end

