# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminFeatureFlagsGet200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :flags
  ]

  @type t :: %__MODULE__{
    :flags => [HookSniffAPI.Model.FeatureFlag.t] | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:flags, :list, HookSniffAPI.Model.FeatureFlag)
  end
end

