# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminRevenueGet200ResponseInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :month,
    :revenue_cents,
    :subscriber_count
  ]

  @type t :: %__MODULE__{
    :month => String.t | nil,
    :revenue_cents => integer() | nil,
    :subscriber_count => integer() | nil
  }

  def decode(value) do
    value
  end
end

