# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AuthLoginPost200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :token,
    :customer,
    :refresh_token,
    :requires_2fa,
    :temp_token,
    :message
  ]

  @type t :: %__MODULE__{
    :token => String.t,
    :customer => HookSniffAPI.Model.CustomerResponse.t,
    :refresh_token => String.t | nil,
    :requires_2fa => boolean(),
    :temp_token => String.t,
    :message => String.t
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:customer, :struct, HookSniffAPI.Model.CustomerResponse)
  end
end

