# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AuthConsentGet200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :consents
  ]

  @type t :: %__MODULE__{
    :consents => %{optional(String.t) => boolean()} | nil
  }

  def decode(value) do
    value
  end
end

