# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Auth2faEnablePost200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :secret,
    :qr_url
  ]

  @type t :: %__MODULE__{
    :secret => String.t | nil,
    :qr_url => String.t | nil
  }

  def decode(value) do
    value
  end
end

