# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Auth2faStatusGet200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :enabled,
    :last_used_at
  ]

  @type t :: %__MODULE__{
    :enabled => boolean() | nil,
    :last_used_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

