# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.BillingPortalPost200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :url
  ]

  @type t :: %__MODULE__{
    :url => String.t | nil
  }

  def decode(value) do
    value
  end
end

