# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.EndpointsEndpointIdTransformsTestPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :payload,
    :rule_id
  ]

  @type t :: %__MODULE__{
    :payload => map() | nil,
    :rule_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

