# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.InboundConfigsIdPutRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :secret,
    :endpoint_id,
    :enabled
  ]

  @type t :: %__MODULE__{
    :secret => String.t | nil,
    :endpoint_id => String.t | nil,
    :enabled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

