# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.NotificationsUnreadCountGet200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :count
  ]

  @type t :: %__MODULE__{
    :count => integer() | nil
  }

  def decode(value) do
    value
  end
end

