# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.PlaygroundGet200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :endpoints,
    :sample_payloads
  ]

  @type t :: %__MODULE__{
    :endpoints => [map()] | nil,
    :sample_payloads => [map()] | nil
  }

  def decode(value) do
    value
  end
end

