# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.PortalNotificationsPut200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :updated,
    :preferences
  ]

  @type t :: %__MODULE__{
    :updated => boolean() | nil,
    :preferences => HookSniffAPI.Model.NotificationPreferences.t | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:preferences, :struct, HookSniffAPI.Model.NotificationPreferences)
  end
end

