# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminRevenueEntry do
  @moduledoc """
  Monthly revenue data point
  """

  @derive JSON.Encoder
  defstruct [
    :date,
    :mrr,
    :new_subscriptions,
    :churns
  ]

  @type t :: %__MODULE__{
    :date => Date.t,
    :mrr => float(),
    :new_subscriptions => integer(),
    :churns => integer()
  }

  def decode(value) do
    value
  end
end

