# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminUpdateAlertRequest do
  @moduledoc """
  Update an alert rule (admin, all fields optional)
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :condition,
    :threshold,
    :channels,
    :is_active
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :condition => String.t | nil,
    :threshold => integer() | nil,
    :channels => [String.t] | nil,
    :is_active => boolean() | nil
  }

  def decode(value) do
    value
  end
end

