# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminAlertRule do
  @moduledoc """
  Admin alert rule with customer info
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :customer_id,
    :customer_email,
    :name,
    :condition,
    :threshold,
    :channels,
    :is_active,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :customer_id => String.t | nil,
    :customer_email => String.t | nil,
    :name => String.t,
    :condition => String.t,
    :threshold => integer(),
    :channels => [String.t],
    :is_active => boolean(),
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

