# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminTestWebhookResponse do
  @moduledoc """
  Result of a test webhook delivery
  """

  @derive JSON.Encoder
  defstruct [
    :status_code,
    :response_body,
    :duration_ms
  ]

  @type t :: %__MODULE__{
    :status_code => integer(),
    :response_body => String.t,
    :duration_ms => integer()
  }

  def decode(value) do
    value
  end
end

