# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminAuditEntry do
  @moduledoc """
  A single admin audit log entry
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :customer_id,
    :action,
    :resource_type,
    :resource_id,
    :details,
    :ip_address,
    :user_agent,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :customer_id => String.t,
    :action => String.t,
    :resource_type => String.t,
    :resource_id => String.t | nil,
    :details => map() | nil,
    :ip_address => String.t | nil,
    :user_agent => String.t | nil,
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

