# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminAuditLogResponse do
  @moduledoc """
  Paginated admin audit log response
  """

  @derive JSON.Encoder
  defstruct [
    :entries,
    :total,
    :page,
    :per_page
  ]

  @type t :: %__MODULE__{
    :entries => [HookSniffAPI.Model.AdminAuditEntry.t],
    :total => integer(),
    :page => integer(),
    :per_page => integer()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:entries, :list, HookSniffAPI.Model.AdminAuditEntry)
  end
end

