# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminRevenueResponse do
  @moduledoc """
  Revenue history for admin analytics
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :total_mrr
  ]

  @type t :: %__MODULE__{
    :data => [HookSniffAPI.Model.AdminRevenueEntry.t],
    :total_mrr => float()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, HookSniffAPI.Model.AdminRevenueEntry)
  end
end

