# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminTestWebhookRequest do
  @moduledoc """
  Send a test HTTP POST to a URL (admin)
  """

  @derive JSON.Encoder
  defstruct [
    :endpoint_url,
    :event_type,
    :payload
  ]

  @type t :: %__MODULE__{
    :endpoint_url => Uri,
    :event_type => String.t | nil,
    :payload => map()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:endpoint_url, :struct, HookSniffAPI.Model.Uri)
  end
end

