# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminSystemStatus do
  @moduledoc """
  System-level status for admin dashboard
  """

  @derive JSON.Encoder
  defstruct [
    :version,
    :uptime_seconds,
    :db_status,
    :redis_status,
    :queue_depth
  ]

  @type t :: %__MODULE__{
    :version => String.t,
    :uptime_seconds => integer(),
    :db_status => String.t,
    :redis_status => String.t,
    :queue_depth => integer()
  }

  def decode(value) do
    value
  end
end

