# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AdminCreateAlertRequest do
  @moduledoc """
  Create a platform alert rule (admin)
  """

  @derive JSON.Encoder
  defstruct [
    :customer_id,
    :name,
    :condition,
    :threshold,
    :channels
  ]

  @type t :: %__MODULE__{
    :customer_id => String.t | nil,
    :name => String.t,
    :condition => String.t,
    :threshold => integer(),
    :channels => [String.t]
  }

  def decode(value) do
    value
  end
end

