# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AlertRuleListResponse do
  @moduledoc """
  Paginated list of alert rules
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :has_more,
    :total
  ]

  @type t :: %__MODULE__{
    :data => [HookSniffAPI.Model.AlertRule.t],
    :has_more => boolean(),
    :total => integer()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, HookSniffAPI.Model.AlertRule)
  end
end

