# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AlertNotificationListResponseDataInner do
  @moduledoc """
  Alert notification entry
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :alert_rule_id,
    :message,
    :channel,
    :status,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :alert_rule_id => String.t | nil,
    :message => String.t | nil,
    :channel => String.t | nil,
    :status => String.t | nil,
    :created_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

