# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AnalyticsTrendResponse do
  @moduledoc """
  Delivery trend data over a time period
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :period
  ]

  @type t :: %__MODULE__{
    :data => [HookSniffAPI.Model.AnalyticsTrendPoint.t],
    :period => String.t
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, HookSniffAPI.Model.AnalyticsTrendPoint)
  end
end

