# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AnalyticsTrendPoint do
  @moduledoc """
  Single data point in a delivery trend
  """

  @derive JSON.Encoder
  defstruct [
    :date,
    :total,
    :successful,
    :failed,
    :avg_latency_ms
  ]

  @type t :: %__MODULE__{
    :date => Date.t,
    :total => integer(),
    :successful => integer(),
    :failed => integer(),
    :avg_latency_ms => float() | nil
  }

  def decode(value) do
    value
  end
end

