# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ApiKeyInfo do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :prefix,
    :created_at,
    :last_used_at,
    :is_active
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :prefix => String.t,
    :created_at => DateTime.t,
    :last_used_at => String.t | nil,
    :is_active => boolean()
  }

  def decode(value) do
    value
  end
end

