# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ApplyTemplateRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :endpoint_id,
    :variables
  ]

  @type t :: %__MODULE__{
    :endpoint_id => String.t,
    :variables => map() | nil
  }

  def decode(value) do
    value
  end
end

