# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Application do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :customer_id,
    :name,
    :description,
    :is_active,
    :endpoint_count,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :customer_id => String.t | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :is_active => boolean() | nil,
    :endpoint_count => integer() | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

