# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.AuditLogEntry do
  @moduledoc """
  A single audit log record
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :actor,
    :action,
    :resource_type,
    :resource_id,
    :timestamp,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :actor => String.t,
    :action => String.t,
    :resource_type => String.t,
    :resource_id => String.t,
    :timestamp => DateTime.t,
    :metadata => map() | nil
  }

  def decode(value) do
    value
  end
end

