# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.BatchResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :deliveries,
    :errors
  ]

  @type t :: %__MODULE__{
    :deliveries => [HookSniffAPI.Model.Delivery.t],
    :errors => [HookSniffAPI.Model.BatchResponseErrorsInner.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:deliveries, :list, HookSniffAPI.Model.Delivery)
     |> Deserializer.deserialize(:errors, :list, HookSniffAPI.Model.BatchResponseErrorsInner)
  end
end

