# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.BatchResponseErrorsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :index,
    :error
  ]

  @type t :: %__MODULE__{
    :index => integer() | nil,
    :error => String.t | nil
  }

  def decode(value) do
    value
  end
end

