# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.BatchWebhookRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :webhooks
  ]

  @type t :: %__MODULE__{
    :webhooks => [HookSniffAPI.Model.CreateWebhookRequest.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:webhooks, :list, HookSniffAPI.Model.CreateWebhookRequest)
  end
end

