# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.BatchReplayRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :ids
  ]

  @type t :: %__MODULE__{
    :ids => [String.t]
  }

  def decode(value) do
    value
  end
end

