# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.BatchWebhookResponse do
  @moduledoc """
  Response for batch webhook delivery creation
  """

  @derive JSON.Encoder
  defstruct [
    :delivery_ids,
    :count
  ]

  @type t :: %__MODULE__{
    :delivery_ids => [String.t],
    :count => integer()
  }

  def decode(value) do
    value
  end
end

