# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.BillingPortalResponse do
  @moduledoc """
  URL for the customer billing portal
  """

  @derive JSON.Encoder
  defstruct [
    :url
  ]

  @type t :: %__MODULE__{
    :url => Uri
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:url, :struct, HookSniffAPI.Model.Uri)
  end
end

