# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CancelSubscriptionRequest do
  @moduledoc """
  Request to cancel current subscription
  """

  @derive JSON.Encoder
  defstruct [
    :reason
  ]

  @type t :: %__MODULE__{
    :reason => String.t
  }

  def decode(value) do
    value
  end
end

