# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CancelSubscriptionResponse do
  @moduledoc """
  Result of subscription cancellation
  """

  @derive JSON.Encoder
  defstruct [
    :cancelled_at,
    :ends_at
  ]

  @type t :: %__MODULE__{
    :cancelled_at => DateTime.t,
    :ends_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

