# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ChurnedUser do
  @moduledoc """
  A user who churned (became inactive) recently
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :email,
    :name,
    :plan,
    :amount,
    :churn_date
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :email => String.t,
    :name => String.t | nil,
    :plan => String.t,
    :amount => float(),
    :churn_date => DateTime.t
  }

  def decode(value) do
    value
  end
end

