# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ChurnResponse do
  @moduledoc """
  Churn report with list of recently churned users
  """

  @derive JSON.Encoder
  defstruct [
    :users
  ]

  @type t :: %__MODULE__{
    :users => [HookSniffAPI.Model.ChurnedUser.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:users, :list, HookSniffAPI.Model.ChurnedUser)
  end
end

