# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Confirm2faRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :code
  ]

  @type t :: %__MODULE__{
    :code => String.t
  }

  def decode(value) do
    value
  end
end

