# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ContactResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :message
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :message => String.t
  }

  def decode(value) do
    value
  end
end

