# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CreateEndpointRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :url,
    :description,
    :allowed_ips,
    :event_filter,
    :custom_headers,
    :retry_policy,
    :routing_strategy,
    :fallback_url,
    :format
  ]

  @type t :: %__MODULE__{
    :url => Uri,
    :description => String.t | nil,
    :allowed_ips => [String.t] | nil,
    :event_filter => [String.t] | nil,
    :custom_headers => map() | nil,
    :retry_policy => HookSniffAPI.Model.RetryPolicy.t | nil,
    :routing_strategy => String.t | nil,
    :fallback_url => Uri | nil,
    :format => String.t | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:url, :struct, HookSniffAPI.Model.Uri)
     |> Deserializer.deserialize(:retry_policy, :struct, HookSniffAPI.Model.RetryPolicy)
     |> Deserializer.deserialize(:fallback_url, :struct, HookSniffAPI.Model.Uri)
  end
end

