# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CreateCustomDomainRequest do
  @moduledoc """
  Register a new custom domain
  """

  @derive JSON.Encoder
  defstruct [
    :domain
  ]

  @type t :: %__MODULE__{
    :domain => String.t
  }

  def decode(value) do
    value
  end
end

