# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CreateRoutingRuleRequest do
  @moduledoc """
  Create a new routing rule
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :conditions,
    :transform,
    :target_endpoint_id
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :conditions => map(),
    :transform => map() | nil,
    :target_endpoint_id => String.t
  }

  def decode(value) do
    value
  end
end

