# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CreateSsoConfigRequest do
  @moduledoc """
  Create a new SSO configuration
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :domain,
    :metadata_url
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :domain => String.t,
    :metadata_url => Uri
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:metadata_url, :struct, HookSniffAPI.Model.Uri)
  end
end

