# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CreateTransformRuleRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :rule_type,
    :config
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :rule_type => String.t,
    :config => map()
  }

  def decode(value) do
    value
  end
end

