# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CreateAlertRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :condition,
    :threshold,
    :channels,
    :endpoint_id
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :condition => String.t,
    :threshold => integer(),
    :channels => [String.t],
    :endpoint_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

