# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CreateApiKeyResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :key,
    :prefix,
    :message
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :key => String.t,
    :prefix => String.t,
    :message => String.t
  }

  def decode(value) do
    value
  end
end

