# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CustomDomainListResponse do
  @moduledoc """
  List of custom domains
  """

  @derive JSON.Encoder
  defstruct [
    :data
  ]

  @type t :: %__MODULE__{
    :data => [HookSniffAPI.Model.CustomDomain.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, HookSniffAPI.Model.CustomDomain)
  end
end

