# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.CustomDomain do
  @moduledoc """
  A custom domain configured for the account
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :domain,
    :status,
    :verification_token,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :domain => String.t,
    :status => String.t,
    :verification_token => String.t | nil,
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

