# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.DailyDeliveryCount do
  @moduledoc """
  Daily delivery count breakdown
  """

  @derive JSON.Encoder
  defstruct [
    :date,
    :total,
    :success,
    :failed
  ]

  @type t :: %__MODULE__{
    :date => Date.t,
    :total => integer(),
    :success => integer(),
    :failed => integer()
  }

  def decode(value) do
    value
  end
end

