# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.DeliveryTrendResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :range,
    :buckets
  ]

  @type t :: %__MODULE__{
    :range => String.t,
    :buckets => [HookSniffAPI.Model.DeliveryTrendResponseBucketsInner.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:buckets, :list, HookSniffAPI.Model.DeliveryTrendResponseBucketsInner)
  end
end

