# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.DeliveryTrendResponseBucketsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :timestamp,
    :successful,
    :failed,
    :total
  ]

  @type t :: %__MODULE__{
    :timestamp => String.t | nil,
    :successful => integer() | nil,
    :failed => integer() | nil,
    :total => integer() | nil
  }

  def decode(value) do
    value
  end
end

