# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Delivery do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :endpoint_id,
    :event,
    :status,
    :attempt_count,
    :response_status,
    :replay_count,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :endpoint_id => String.t,
    :event => String.t | nil,
    :status => String.t,
    :attempt_count => integer(),
    :response_status => integer() | nil,
    :replay_count => integer(),
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

