# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.DeliveryDetailResponse do
  @moduledoc """
  Full delivery detail including all retry attempts and endpoint info
  """

  @derive JSON.Encoder
  defstruct [
    :delivery,
    :attempts,
    :endpoint,
    :request_headers,
    :request_body,
    :response_headers
  ]

  @type t :: %__MODULE__{
    :delivery => HookSniffAPI.Model.Delivery.t,
    :attempts => [HookSniffAPI.Model.DeliveryAttempt.t],
    :endpoint => HookSniffAPI.Model.Endpoint.t | nil,
    :request_headers => map() | nil,
    :request_body => map() | nil,
    :response_headers => map() | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:delivery, :struct, HookSniffAPI.Model.Delivery)
     |> Deserializer.deserialize(:attempts, :list, HookSniffAPI.Model.DeliveryAttempt)
     |> Deserializer.deserialize(:endpoint, :struct, HookSniffAPI.Model.Endpoint)
  end
end

