# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.DeliveryAttempt do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :attempt_number,
    :status_code,
    :response_body,
    :duration_ms,
    :error_message,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :attempt_number => integer(),
    :status_code => integer() | nil,
    :response_body => String.t | nil,
    :duration_ms => integer() | nil,
    :error_message => String.t | nil,
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

