# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.DeployInfo do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :version,
    :git_commit,
    :build_time,
    :environment
  ]

  @type t :: %__MODULE__{
    :version => String.t | nil,
    :git_commit => String.t | nil,
    :build_time => String.t | nil,
    :environment => String.t | nil
  }

  def decode(value) do
    value
  end
end

