# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.DeviceTokenResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :token,
    :platform,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :token => String.t,
    :platform => String.t,
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

