# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.DomainDnsRecord do
  @moduledoc """
  A DNS record required for domain verification
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :name,
    :value,
    :status
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :name => String.t,
    :value => String.t,
    :status => String.t
  }

  def decode(value) do
    value
  end
end

