# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.EmbedConfigTheme do
  @moduledoc """
  Visual customization for the embed
  """

  @derive JSON.Encoder
  defstruct [
    :primary_color,
    :background_color,
    :font_family
  ]

  @type t :: %__MODULE__{
    :primary_color => String.t | nil,
    :background_color => String.t | nil,
    :font_family => String.t | nil
  }

  def decode(value) do
    value
  end
end

