# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.EmbedConfig do
  @moduledoc """
  Configuration for embedded webhook dashboard
  """

  @derive JSON.Encoder
  defstruct [
    :allowed_origins,
    :theme,
    :features
  ]

  @type t :: %__MODULE__{
    :allowed_origins => [String.t],
    :theme => HookSniffAPI.Model.EmbedConfigTheme.t | nil,
    :features => [String.t] | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:theme, :struct, HookSniffAPI.Model.EmbedConfigTheme)
  end
end

