# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Enable2faResponse do
  @moduledoc """
  TOTP secret and QR code URL returned after enabling 2FA
  """

  @derive JSON.Encoder
  defstruct [
    :secret,
    :qr_url
  ]

  @type t :: %__MODULE__{
    :secret => String.t,
    :qr_url => Uri
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:qr_url, :struct, HookSniffAPI.Model.Uri)
  end
end

