# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.EndpointListResponse do
  @moduledoc """
  Paginated list of endpoints
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :total,
    :has_more
  ]

  @type t :: %__MODULE__{
    :data => [HookSniffAPI.Model.Endpoint.t],
    :total => integer(),
    :has_more => boolean()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, HookSniffAPI.Model.Endpoint)
  end
end

