# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Endpoint do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :url,
    :description,
    :is_active,
    :retry_policy,
    :created_at,
    :allowed_ips,
    :event_filter,
    :custom_headers,
    :routing_strategy,
    :fallback_url,
    :avg_response_ms,
    :failure_streak,
    :format
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :url => Uri,
    :description => String.t | nil,
    :is_active => boolean(),
    :retry_policy => HookSniffAPI.Model.RetryPolicy.t,
    :created_at => DateTime.t,
    :allowed_ips => [String.t] | nil,
    :event_filter => [String.t] | nil,
    :custom_headers => map() | nil,
    :routing_strategy => String.t,
    :fallback_url => Uri | nil,
    :avg_response_ms => integer(),
    :failure_streak => integer(),
    :format => String.t
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:url, :struct, HookSniffAPI.Model.Uri)
     |> Deserializer.deserialize(:retry_policy, :struct, HookSniffAPI.Model.RetryPolicy)
     |> Deserializer.deserialize(:fallback_url, :struct, HookSniffAPI.Model.Uri)
  end
end

