# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.EventType do
  @moduledoc """
  A registered event type in the system
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :schema_id
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :description => String.t | nil,
    :schema_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

