# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.EventTypeCount do
  @moduledoc """
  Event type occurrence count
  """

  @derive JSON.Encoder
  defstruct [
    :event,
    :count
  ]

  @type t :: %__MODULE__{
    :event => String.t | nil,
    :count => integer()
  }

  def decode(value) do
    value
  end
end

