# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ExportDataResponse do
  @moduledoc """
  GDPR data export containing all user data
  """

  @derive JSON.Encoder
  defstruct [
    :user,
    :endpoints,
    :deliveries,
    :teams,
    :exported_at
  ]

  @type t :: %__MODULE__{
    :user => HookSniffAPI.Model.CustomerResponse.t | nil,
    :endpoints => [HookSniffAPI.Model.Endpoint.t] | nil,
    :deliveries => [HookSniffAPI.Model.Delivery.t] | nil,
    :teams => [HookSniffAPI.Model.Team.t] | nil,
    :exported_at => DateTime.t
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:user, :struct, HookSniffAPI.Model.CustomerResponse)
     |> Deserializer.deserialize(:endpoints, :list, HookSniffAPI.Model.Endpoint)
     |> Deserializer.deserialize(:deliveries, :list, HookSniffAPI.Model.Delivery)
     |> Deserializer.deserialize(:teams, :list, HookSniffAPI.Model.Team)
  end
end

