# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.FeatureFlag do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :is_enabled,
    :rollout_percentage,
    :enabled_for_plans,
    :created_by,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :is_enabled => boolean() | nil,
    :rollout_percentage => integer() | nil,
    :enabled_for_plans => [String.t] | nil,
    :created_by => String.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

