# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.InboundWebhookResponse do
  @moduledoc """
  Result of processing an inbound webhook
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :status,
    :endpoint_id,
    :received_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :status => String.t,
    :endpoint_id => String.t,
    :received_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

