# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.InboundConfig do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :customer_id,
    :provider,
    :secret,
    :endpoint_id,
    :enabled,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :customer_id => String.t | nil,
    :provider => String.t | nil,
    :secret => String.t | nil,
    :endpoint_id => String.t | nil,
    :enabled => boolean() | nil,
    :created_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

