# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.InboundWebhookRequest do
  @moduledoc """
  Raw webhook payload received from an external provider (Stripe, GitHub, etc.)
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :payload,
    :headers
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :payload => map(),
    :headers => map() | nil
  }

  def decode(value) do
    value
  end
end

