# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.InvoiceResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :amount_cents,
    :currency,
    :status,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :amount_cents => integer(),
    :currency => String.t,
    :status => String.t,
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

