# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.LatencyResponse do
  @moduledoc """
  Latency percentile breakdown for deliveries
  """

  @derive JSON.Encoder
  defstruct [
    :p50,
    :p90,
    :p95,
    :p99,
    :period
  ]

  @type t :: %__MODULE__{
    :p50 => float(),
    :p90 => float(),
    :p95 => float(),
    :p99 => float(),
    :period => String.t
  }

  def decode(value) do
    value
  end
end

