# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.LatencyTrendResponseBucketsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :timestamp,
    :avg_ms,
    :p95_ms
  ]

  @type t :: %__MODULE__{
    :timestamp => String.t | nil,
    :avg_ms => number() | nil,
    :p95_ms => number() | nil
  }

  def decode(value) do
    value
  end
end

