# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.LatencyTrendResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :range,
    :buckets,
    :overall_avg_ms
  ]

  @type t :: %__MODULE__{
    :range => String.t,
    :buckets => [HookSniffAPI.Model.LatencyTrendResponseBucketsInner.t],
    :overall_avg_ms => number()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:buckets, :list, HookSniffAPI.Model.LatencyTrendResponseBucketsInner)
  end
end

