# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.NotificationListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :notifications,
    :total,
    :unread_count
  ]

  @type t :: %__MODULE__{
    :notifications => [HookSniffAPI.Model.Notification.t],
    :total => integer(),
    :unread_count => integer()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:notifications, :list, HookSniffAPI.Model.Notification)
  end
end

