# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.NotificationPreferences do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email_on_failure,
    :email_on_dead_letter,
    :email_on_success,
    :slack_webhook_url,
    :discord_webhook_url,
    :webhook_url
  ]

  @type t :: %__MODULE__{
    :email_on_failure => boolean(),
    :email_on_dead_letter => boolean(),
    :email_on_success => boolean(),
    :slack_webhook_url => String.t | nil,
    :discord_webhook_url => String.t | nil,
    :webhook_url => String.t | nil
  }

  def decode(value) do
    value
  end
end

