# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Notification do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :title,
    :body,
    :is_read,
    :link,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :title => String.t,
    :body => String.t,
    :is_read => boolean(),
    :link => String.t | nil,
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

