# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.OAuthLoginRedirect do
  @moduledoc """
  OAuth redirect information
  """

  @derive JSON.Encoder
  defstruct [
    :redirect_url
  ]

  @type t :: %__MODULE__{
    :redirect_url => Uri
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:redirect_url, :struct, HookSniffAPI.Model.Uri)
  end
end

