# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.OAuthCallbackRequest do
  @moduledoc """
  OAuth authorization callback parameters
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :state,
    :redirect_uri
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :state => String.t,
    :redirect_uri => Uri | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:redirect_uri, :struct, HookSniffAPI.Model.Uri)
  end
end

