# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.OAuthProvider do
  @moduledoc """
  An available OAuth identity provider
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :client_id,
    :authorize_url,
    :token_url
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :client_id => String.t,
    :authorize_url => Uri,
    :token_url => Uri
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:authorize_url, :struct, HookSniffAPI.Model.Uri)
     |> Deserializer.deserialize(:token_url, :struct, HookSniffAPI.Model.Uri)
  end
end

