# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.PaginatedUsers do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :users,
    :total,
    :page,
    :per_page
  ]

  @type t :: %__MODULE__{
    :users => [HookSniffAPI.Model.UserSummary.t],
    :total => integer(),
    :page => integer(),
    :per_page => integer()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:users, :list, HookSniffAPI.Model.UserSummary)
  end
end

