# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.PlatformSettings do
  @moduledoc """
  Platform-wide configuration settings
  """

  @derive JSON.Encoder
  defstruct [
    :default_plan,
    :max_endpoints_free,
    :max_endpoints_pro,
    :max_webhooks_free,
    :max_webhooks_pro,
    :rate_limit_free,
    :rate_limit_pro,
    :retry_max_attempts,
    :retention_days_free,
    :retention_days_pro,
    :maintenance_mode,
    :signup_enabled,
    :plan_price_pro,
    :plan_price_business,
    :resend_api_key,
    :email_sender
  ]

  @type t :: %__MODULE__{
    :default_plan => String.t,
    :max_endpoints_free => integer(),
    :max_endpoints_pro => integer(),
    :max_webhooks_free => integer(),
    :max_webhooks_pro => integer(),
    :rate_limit_free => integer(),
    :rate_limit_pro => integer(),
    :retry_max_attempts => integer(),
    :retention_days_free => integer(),
    :retention_days_pro => integer(),
    :maintenance_mode => boolean(),
    :signup_enabled => boolean(),
    :plan_price_pro => float(),
    :plan_price_business => float(),
    :resend_api_key => String.t | nil,
    :email_sender => String.t | nil
  }

  def decode(value) do
    value
  end
end

