# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.PlaygroundTestResponse do
  @moduledoc """
  Result of a playground test delivery
  """

  @derive JSON.Encoder
  defstruct [
    :status_code,
    :response_body,
    :latency_ms,
    :headers
  ]

  @type t :: %__MODULE__{
    :status_code => integer(),
    :response_body => String.t,
    :latency_ms => integer(),
    :headers => map() | nil
  }

  def decode(value) do
    value
  end
end

