# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.PlaygroundTestRequest do
  @moduledoc """
  Test a webhook payload against an endpoint in sandbox
  """

  @derive JSON.Encoder
  defstruct [
    :endpoint_id,
    :payload,
    :headers
  ]

  @type t :: %__MODULE__{
    :endpoint_id => String.t,
    :payload => map(),
    :headers => map() | nil
  }

  def decode(value) do
    value
  end
end

