# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.PortalConfig do
  @moduledoc """
  Customer-facing portal branding and configuration
  """

  @derive JSON.Encoder
  defstruct [
    :logo_url,
    :primary_color,
    :custom_domain,
    :webhook_events
  ]

  @type t :: %__MODULE__{
    :logo_url => Uri | nil,
    :primary_color => String.t | nil,
    :custom_domain => String.t | nil,
    :webhook_events => [String.t] | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:logo_url, :struct, HookSniffAPI.Model.Uri)
  end
end

