# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.PortalSession do
  @moduledoc """
  Temporary session token for the customer portal
  """

  @derive JSON.Encoder
  defstruct [
    :token,
    :expires_at,
    :url
  ]

  @type t :: %__MODULE__{
    :token => String.t,
    :expires_at => DateTime.t,
    :url => Uri
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:url, :struct, HookSniffAPI.Model.Uri)
  end
end

