# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.RateLimitUsage do
  @moduledoc """
  Current rate limit usage for an endpoint
  """

  @derive JSON.Encoder
  defstruct [
    :current_rps,
    :limit_rps,
    :remaining,
    :reset_at
  ]

  @type t :: %__MODULE__{
    :current_rps => float(),
    :limit_rps => float(),
    :remaining => float(),
    :reset_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

