# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.RateLimitConfig do
  @moduledoc """
  Rate limiting configuration for an endpoint
  """

  @derive JSON.Encoder
  defstruct [
    :requests_per_second,
    :burst_size,
    :enabled
  ]

  @type t :: %__MODULE__{
    :requests_per_second => integer(),
    :burst_size => integer(),
    :enabled => boolean()
  }

  def decode(value) do
    value
  end
end

