# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.RegisterRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :password,
    :name
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :password => String.t | nil,
    :name => String.t | nil
  }

  def decode(value) do
    value
  end
end

