# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ReplayDeliveryResponse do
  @moduledoc """
  Result of replaying a delivery
  """

  @derive JSON.Encoder
  defstruct [
    :message,
    :original_id,
    :new_delivery_id
  ]

  @type t :: %__MODULE__{
    :message => String.t,
    :original_id => String.t,
    :new_delivery_id => String.t
  }

  def decode(value) do
    value
  end
end

