# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.RetryPolicy do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :max_attempts,
    :backoff,
    :initial_delay_secs,
    :max_delay_secs
  ]

  @type t :: %__MODULE__{
    :max_attempts => integer(),
    :backoff => String.t,
    :initial_delay_secs => integer(),
    :max_delay_secs => integer()
  }

  def decode(value) do
    value
  end
end

