# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.RevenueResponse do
  @moduledoc """
  Full revenue analytics response
  """

  @derive JSON.Encoder
  defstruct [
    :monthly_revenue,
    :revenue_by_plan,
    :mrr,
    :churn_rate,
    :mrr_trend
  ]

  @type t :: %__MODULE__{
    :monthly_revenue => [HookSniffAPI.Model.RevenueResponseMonthlyRevenueInner.t],
    :revenue_by_plan => [HookSniffAPI.Model.RevenueResponseRevenueByPlanInner.t],
    :mrr => float(),
    :churn_rate => float(),
    :mrr_trend => float()
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:monthly_revenue, :list, HookSniffAPI.Model.RevenueResponseMonthlyRevenueInner)
     |> Deserializer.deserialize(:revenue_by_plan, :list, HookSniffAPI.Model.RevenueResponseRevenueByPlanInner)
  end
end

