# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.RotateSecretResponse do
  @moduledoc """
  New signing secret after rotation
  """

  @derive JSON.Encoder
  defstruct [
    :secret
  ]

  @type t :: %__MODULE__{
    :secret => String.t
  }

  def decode(value) do
    value
  end
end

