# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.RoutingInfo do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :endpoint_id,
    :routing_strategy,
    :fallback_url,
    :avg_response_ms,
    :failure_streak,
    :is_healthy
  ]

  @type t :: %__MODULE__{
    :endpoint_id => String.t,
    :routing_strategy => String.t,
    :fallback_url => String.t | nil,
    :avg_response_ms => integer(),
    :failure_streak => integer(),
    :is_healthy => boolean()
  }

  def decode(value) do
    value
  end
end

