# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.RoutingRuleListResponseDataInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :conditions,
    :transform,
    :target_endpoint_id,
    :enabled,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :conditions => map(),
    :transform => map() | nil,
    :target_endpoint_id => String.t,
    :enabled => boolean() | nil,
    :created_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

