# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SchemaResponse do
  @moduledoc """
  A registered JSON Schema for event validation
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :version,
    :schema_json,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :version => integer(),
    :schema_json => map(),
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

