# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SearchRequest do
  @moduledoc """
  Search request for webhook deliveries
  """

  @derive JSON.Encoder
  defstruct [
    :query,
    :filters,
    :page,
    :per_page
  ]

  @type t :: %__MODULE__{
    :query => String.t,
    :filters => HookSniffAPI.Model.SearchRequestFilters.t | nil,
    :page => integer() | nil,
    :per_page => integer() | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:filters, :struct, HookSniffAPI.Model.SearchRequestFilters)
  end
end

