# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SearchRequestFilters do
  @moduledoc """
  Additional filters (status, endpoint_id, etc.)
  """

  @derive JSON.Encoder
  defstruct [
    :status,
    :endpoint_id
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil,
    :endpoint_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

