# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ServiceTokenCreateResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :token,
    :token_prefix,
    :message
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :token => String.t | nil,
    :token_prefix => String.t | nil,
    :message => String.t | nil
  }

  def decode(value) do
    value
  end
end

