# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ServiceToken do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :token_prefix,
    :created_at,
    :last_used_at,
    :is_active
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :token_prefix => String.t | nil,
    :created_at => DateTime.t | nil,
    :last_used_at => DateTime.t | nil,
    :is_active => boolean() | nil
  }

  def decode(value) do
    value
  end
end

