# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SimulatorResponse do
  @moduledoc """
  Result of a simulated webhook delivery
  """

  @derive JSON.Encoder
  defstruct [
    :delivery_id,
    :status,
    :latency_ms
  ]

  @type t :: %__MODULE__{
    :delivery_id => String.t,
    :status => String.t,
    :latency_ms => integer()
  }

  def decode(value) do
    value
  end
end

