# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SimulatorRequest do
  @moduledoc """
  Send a simulated webhook event
  """

  @derive JSON.Encoder
  defstruct [
    :endpoint_id,
    :event_type,
    :payload,
    :delay_ms
  ]

  @type t :: %__MODULE__{
    :endpoint_id => String.t,
    :event_type => String.t,
    :payload => map(),
    :delay_ms => integer() | nil
  }

  def decode(value) do
    value
  end
end

