# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SsoConfig do
  @moduledoc """
  Single Sign-On configuration (SAML or OIDC)
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :domain,
    :entity_id,
    :sso_url,
    :certificate
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :domain => String.t,
    :entity_id => String.t | nil,
    :sso_url => Uri | nil,
    :certificate => String.t | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:sso_url, :struct, HookSniffAPI.Model.Uri)
  end
end

