# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.StatsResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  @derive Jason.Encoder
  defstruct [
    :total_deliveries,
    :successful_deliveries,
    :failed_deliveries,
    :total_endpoints,
    :active_endpoints,
    :plan,
    :webhook_limit,
    :webhook_count
  ]

  @type t :: %__MODULE__{
    :total_deliveries => integer(),
    :successful_deliveries => integer(),
    :failed_deliveries => integer(),
    :total_endpoints => integer(),
    :active_endpoints => integer(),
    :plan => String.t,
    :webhook_limit => integer(),
    :webhook_count => integer()
  }

  def decode(value) do
    value
  end
end

