# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.StreamParams do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :endpoint_id,
    :status,
    :limit
  ]

  @type t :: %__MODULE__{
    :endpoint_id => String.t,
    :status => String.t,
    :limit => integer()
  }

  def decode(value) do
    value
  end
end

