# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SubscriptionResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :plan,
    :status,
    :payment_provider,
    :webhook_limit,
    :endpoint_limit,
    :retention_days,
    :monthly_price_cents
  ]

  @type t :: %__MODULE__{
    :plan => String.t,
    :status => String.t,
    :payment_provider => String.t,
    :webhook_limit => integer(),
    :endpoint_limit => integer(),
    :retention_days => integer(),
    :monthly_price_cents => integer()
  }

  def decode(value) do
    value
  end
end

