# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SuccessRateResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :range,
    :successful,
    :failed,
    :pending,
    :success_rate
  ]

  @type t :: %__MODULE__{
    :range => String.t,
    :successful => integer(),
    :failed => integer(),
    :pending => integer(),
    :success_rate => float()
  }

  def decode(value) do
    value
  end
end

