# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SystemStats do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :total_users,
    :active_users,
    :total_endpoints,
    :total_deliveries,
    :plan_breakdown
  ]

  @type t :: %__MODULE__{
    :total_users => integer(),
    :active_users => integer(),
    :total_endpoints => integer(),
    :total_deliveries => integer(),
    :plan_breakdown => [HookSniffAPI.Model.SystemStatsPlanBreakdownInner.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:plan_breakdown, :list, HookSniffAPI.Model.SystemStatsPlanBreakdownInner)
  end
end

