# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SystemStatus do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :overall_status,
    :uptime_30d,
    :components,
    :checked_at
  ]

  @type t :: %__MODULE__{
    :overall_status => String.t,
    :uptime_30d => number(),
    :components => [HookSniffAPI.Model.SystemStatusComponentsInner.t],
    :checked_at => String.t
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:components, :list, HookSniffAPI.Model.SystemStatusComponentsInner)
  end
end

