# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.SystemStatusComponentsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :status,
    :latency_ms,
    :description,
    :last_checked
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :status => String.t | nil,
    :latency_ms => integer() | nil,
    :description => String.t | nil,
    :last_checked => String.t | nil
  }

  def decode(value) do
    value
  end
end

