# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.TeamInvite do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :email,
    :role,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :email => String.t,
    :role => String.t,
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

