# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.TeamDetailResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :team,
    :members,
    :invites
  ]

  @type t :: %__MODULE__{
    :team => HookSniffAPI.Model.Team.t,
    :members => [HookSniffAPI.Model.TeamMember.t],
    :invites => [HookSniffAPI.Model.TeamInvite.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:team, :struct, HookSniffAPI.Model.Team)
     |> Deserializer.deserialize(:members, :list, HookSniffAPI.Model.TeamMember)
     |> Deserializer.deserialize(:invites, :list, HookSniffAPI.Model.TeamInvite)
  end
end

