# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.TeamMember do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :user_id,
    :email,
    :name,
    :role,
    :joined_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :user_id => String.t,
    :email => String.t,
    :name => String.t | nil,
    :role => String.t,
    :joined_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

