# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.TemplateListResponse do
  @moduledoc """
  Paginated list of webhook payload templates
  """

  @derive JSON.Encoder
  defstruct [
    :data
  ]

  @type t :: %__MODULE__{
    :data => [HookSniffAPI.Model.WebhookTemplate.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, HookSniffAPI.Model.WebhookTemplate)
  end
end

