# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.TestWebhookResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :status_code,
    :duration_ms,
    :response_body
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :status_code => integer(),
    :duration_ms => integer(),
    :response_body => String.t
  }

  def decode(value) do
    value
  end
end

