# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.TransformRule do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :endpoint_id,
    :name,
    :rule_type,
    :config,
    :is_active,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :endpoint_id => String.t,
    :name => String.t,
    :rule_type => String.t,
    :config => map() | nil,
    :is_active => boolean(),
    :created_at => DateTime.t
  }

  def decode(value) do
    value
  end
end

