# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.TwoFactorRequiredResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :requires_2fa,
    :temp_token,
    :message
  ]

  @type t :: %__MODULE__{
    :requires_2fa => boolean(),
    :temp_token => String.t,
    :message => String.t
  }

  def decode(value) do
    value
  end
end

