# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UpdateSubscriptionRequest do
  @moduledoc """
  Request to change subscription plan
  """

  @derive JSON.Encoder
  defstruct [
    :plan,
    :proration
  ]

  @type t :: %__MODULE__{
    :plan => String.t,
    :proration => boolean() | nil
  }

  def decode(value) do
    value
  end
end

