# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UpdateTransformRuleRequest do
  @moduledoc """
  Update an existing transform rule (all fields optional)
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :config
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :config => map() | nil
  }

  def decode(value) do
    value
  end
end

