# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UpdateRoutingRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :routing_strategy,
    :fallback_url
  ]

  @type t :: %__MODULE__{
    :routing_strategy => String.t,
    :fallback_url => Uri
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:fallback_url, :struct, HookSniffAPI.Model.Uri)
  end
end

