# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UpdateRoutingRuleRequest do
  @moduledoc """
  Update an existing routing rule (all fields optional)
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :conditions,
    :transform
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :conditions => map() | nil,
    :transform => map() | nil
  }

  def decode(value) do
    value
  end
end

