# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UpdateSsoConfigRequest do
  @moduledoc """
  Update an SSO configuration (all fields optional)
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :domain
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :domain => String.t
  }

  def decode(value) do
    value
  end
end

