# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UpdateAlertRuleRequest do
  @moduledoc """
  Request to update an existing alert rule (all fields optional)
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :condition,
    :threshold,
    :channels
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :condition => String.t,
    :threshold => integer(),
    :channels => [String.t]
  }

  def decode(value) do
    value
  end
end

