# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UpgradeResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :checkout_url,
    :provider,
    :message
  ]

  @type t :: %__MODULE__{
    :checkout_url => String.t | nil,
    :provider => String.t,
    :message => String.t
  }

  def decode(value) do
    value
  end
end

