# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UpgradeRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :plan,
    :provider
  ]

  @type t :: %__MODULE__{
    :plan => String.t,
    :provider => String.t | nil
  }

  def decode(value) do
    value
  end
end

