# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UsageStatsResponse do
  @moduledoc """
  Account usage statistics summary
  """

  @derive JSON.Encoder
  defstruct [
    :endpoints_count,
    :deliveries_count,
    :teams_count,
    :storage_used_bytes
  ]

  @type t :: %__MODULE__{
    :endpoints_count => integer(),
    :deliveries_count => integer(),
    :teams_count => integer(),
    :storage_used_bytes => integer()
  }

  def decode(value) do
    value
  end
end

