# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UsageResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :plan,
    :period_start,
    :period_end,
    :webhooks_used,
    :webhooks_limit,
    :endpoints_used,
    :endpoints_limit
  ]

  @type t :: %__MODULE__{
    :plan => String.t,
    :period_start => DateTime.t,
    :period_end => DateTime.t,
    :webhooks_used => integer(),
    :webhooks_limit => integer(),
    :endpoints_used => integer(),
    :endpoints_limit => integer()
  }

  def decode(value) do
    value
  end
end

