# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.UserAnalytics do
  @moduledoc """
  User analytics data for admin view
  """

  @derive JSON.Encoder
  defstruct [
    :daily_deliveries,
    :top_events,
    :endpoint_health
  ]

  @type t :: %__MODULE__{
    :daily_deliveries => [HookSniffAPI.Model.DailyDeliveryCount.t],
    :top_events => [HookSniffAPI.Model.EventTypeCount.t],
    :endpoint_health => [HookSniffAPI.Model.EndpointHealth.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:daily_deliveries, :list, HookSniffAPI.Model.DailyDeliveryCount)
     |> Deserializer.deserialize(:top_events, :list, HookSniffAPI.Model.EventTypeCount)
     |> Deserializer.deserialize(:endpoint_health, :list, HookSniffAPI.Model.EndpointHealth)
  end
end

