# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ValidateEventResponse do
  @moduledoc """
  Result of validating an event payload against a schema
  """

  @derive JSON.Encoder
  defstruct [
    :valid,
    :errors
  ]

  @type t :: %__MODULE__{
    :valid => boolean(),
    :errors => [HookSniffAPI.Model.ValidateEventResponseErrorsInner.t] | nil
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:errors, :list, HookSniffAPI.Model.ValidateEventResponseErrorsInner)
  end
end

