# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ValidateEventRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :event
  ]

  @type t :: %__MODULE__{
    :event => map()
  }

  def decode(value) do
    value
  end
end

