# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.ValidateEventResponseErrorsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :path,
    :message
  ]

  @type t :: %__MODULE__{
    :path => String.t | nil,
    :message => String.t | nil
  }

  def decode(value) do
    value
  end
end

