# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.VerifyEmailRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :token
  ]

  @type t :: %__MODULE__{
    :token => String.t
  }

  def decode(value) do
    value
  end
end

