# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.VerifyCustomDomainResponse do
  @moduledoc """
  Result of domain verification attempt
  """

  @derive JSON.Encoder
  defstruct [
    :status,
    :dns_records
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :dns_records => [HookSniffAPI.Model.DomainDnsRecord.t]
  }

  alias HookSniffAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:dns_records, :list, HookSniffAPI.Model.DomainDnsRecord)
  end
end

