# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Verify2faRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :temp_token,
    :code
  ]

  @type t :: %__MODULE__{
    :temp_token => String.t,
    :code => String.t
  }

  def decode(value) do
    value
  end
end

