# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.WebhookFilter do
  @moduledoc """
  Query parameters for filtering webhook deliveries
  """

  @derive JSON.Encoder
  defstruct [
    :status,
    :endpoint_id,
    :event_type,
    :from_date,
    :to_date,
    :page,
    :per_page
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :endpoint_id => String.t,
    :event_type => String.t,
    :from_date => DateTime.t,
    :to_date => DateTime.t,
    :page => integer(),
    :per_page => integer()
  }

  def decode(value) do
    value
  end
end

