# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.WebhookTemplate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :category,
    :payload_template
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :description => String.t,
    :category => String.t,
    :payload_template => map() | nil
  }

  def decode(value) do
    value
  end
end

